CREATE DATABASE $DATABASE_NAME;
 
CREATE USER $USER_NAME WITH PASSWORD '$USER_PASSWORD';
 
ALTER ROLE codez SET client_encoding TO 'utf8';
ALTER ROLE codez SET default_transaction_isolation TO 'read committed';
ALTER ROLE codez SET timezone TO 'UTC';
 
GRANT ALL PRIVILEGES ON DATABASE $DATABASE_NAME TO $USER_NAME;
